[package]
name = "proforma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.12.1"
imgui = "0.10.0"
num-traits = "0.2.15"
sdl2 = "0.35.2"
